---
- hosts: web
  become: yes
  tasks:
          - name: install httpd
            yum:
                    name: httpd
                    state: present
          - name: start apache server and enable it
            service:
                    name: httpd
                    enabled: true
                    state: started
          - name: create index.html
            copy:
                    src: index.html
                    dest: /var/www/html/
                    mode: 0444
